Repository atlp-rwanda/code-ninjas-fe, pull requests merged in 2022-06, with the labels that each got.

#13 #181414717 (Feature): reset password
  package.json
  src/App.jsx
  src/components/forgetPassword/forgotPassword.jsx
  src/components/login/loginForm.jsx
  src/components/resetPassword/resetPassword.jsx
  src/pages/forgetPassword.jsx
  src/pages/resetPassword.jsx
  src/styles/colorVariables.js
  src/styles/registration.scss
  src/styles/variable.scss
  src/tests/resetpassword.test.js
  src/utility/api.js
  src/validation/emailValidation.js
  src/validation/resetValidation.js
  yarn.lock
Labels: Ready for review

#17 181414723 (Feature): Implement dashboard main panel
  .DS_Store
  _mock/account.jsx
  _mock/user.jsx
  package.json
  public/.DS_Store
  public/static/icons/ic_flag_de.svg
  public/static/icons/ic_flag_en.svg
  public/static/icons/ic_flag_fr.svg
  public/static/icons/ic_notification_chat.svg
  public/static/icons/ic_notification_mail.svg
  public/static/icons/ic_notification_package.svg
  public/static/icons/ic_notification_shipping.svg
  public/static/icons/shape-avatar.svg
  public/static/mock-images/avatars/avatar_default.jpg
  src/App.jsx
  src/app/bounce.jsx
  src/components/dashboard/Iconify.jsx
  src/components/dashboard/MenuPopover.jsx
  src/components/dashboard/NavSection.jsx
  src/components/dashboard/Page.jsx
  src/components/dashboard/Scrollbar.jsx
  src/components/home/home.scss
  src/hooks/useResponsive.jsx
  src/layouts/AccountPopover.jsx
  src/layouts/DashboardNavbar.jsx
  src/layouts/DashboardSidebar.jsx
  src/layouts/NavConfig.jsx
  src/layouts/NotificationsPopover.jsx
  src/layouts/Searchbar.jsx
  src/layouts/index.jsx
  src/pages/Accommodations.jsx
  src/pages/Chat.jsx
  src/pages/DashboardApp.jsx
  src/pages/Profile.jsx
  src/pages/TripRequest.jsx
  src/pages/Users.jsx
  src/pages/controlpannel.jsx
  src/redux/features/auth/loginSlice.js
  src/styles/registration.scss
  src/tests/__snapshots__/dashboard.test.js.snap
  src/tests/dashboard.test.js
  utils/formatTime.jsx
  vercel.json
  yarn.lock
Labels: Ready for review

#19 181414721 (Feature): Implement request table
  .DS_Store
  package.json
  src/components/login/loginForm.jsx
  src/components/request/Table.jsx
  src/layouts/DashboardSidebar.jsx
  src/pages/TripRequest.jsx
  src/pages/request.jsx
  src/redux/features/auth/isLoggedSlice.js
  src/redux/features/profile/profileSlice.js
  src/redux/reducers.js
  src/redux/store.js
  src/styles/Table.scss
  src/tests/__snapshots__/dashboard.test.js.snap
  src/tests/dashboard.test.js
  src/tests/requestTable.test.js
  yarn.lock
Labels: Needs Merge

#20 ft(Verification Page)
  package.json
  src/App.jsx
  src/components/verification/loaderContainer.jsx
  src/pages/VerificationPage.jsx
  yarn.lock
Labels: Ready for review

#21 ft-role-setting
  package.json
  src/App.jsx
  src/app/superAdmin.jsx
  src/components/login/loginForm.jsx
  src/components/registration/registrationForm.jsx
  src/components/role/MaterialTableIcons.js
  src/components/role/table.js
  src/layouts/AccountPopover.jsx
  src/layouts/DashboardSidebar.jsx
  src/layouts/NavConfig.jsx
  src/pages/Users.jsx
  src/pages/role.jsx
  src/redux/features/auth/loginSlice.js
  src/styles/hideUser.scss
  src/styles/roleFix.scss
  src/styles/variable.scss
  src/tests/__snapshots__/dashboard.test.js.snap
  src/tests/dashboard.test.js
  src/tests/roleTable.test.js
  yarn.lock
Labels: Ready for review

#24 #181414720 User profile settings
  .babelrc
  package.json
  src/.DS_Store
  src/app/bounce.jsx
  src/components/.DS_Store
  src/components/profile/Profile.jsx
  src/components/role/table.js
  src/components/validations/profileCompleteValidation.js
  src/components/validations/profileUpdateValidation.js
  src/components/validations/validationSchema.js
  src/pages/Profile.jsx
  src/redux/features/profile/profileSlice.js
  src/redux/reducers.js
  src/styles/colorVariables.jsx
  src/tests/__snapshots__/dashboard.test.js.snap
  src/tests/dashboard.test.js
  src/tests/profile.test.js
  src/validation/registrationValidation.jsx
  yarn.lock
Labels: enhancement, Ready for review
